### ISSUE TITLE
希望有个function list和更详细的安装使用文档

### ISSUE THREAD

**Issue by JasonMa0012** [Ubpa/UGM#1]
初学C++，配置CMake很费劲，安装完新建工程后include，发现编译时还是需要需要联网下载几个U库到out文件夹，不知道是错误还是本应如此。另外由于C++不是很熟，发现在main文件最后include和一些有嵌套的头文件中include会导致编译错误，挪几行到其他include上面就没有错误，想请教下include有什么要注意的吗

**Comment by Ubpa** [comment]
ok，稍后

**Comment by Ubpa** [comment]
已补充
关于 include 的问题，跟编译器有关，目前我仅在 VS2019 上测试，看你的描述像是用了其他编译器

**Comment by JasonMa0012** [comment]
感谢。
我也是VS2019，默认的MSVC，除了初次编译时需要重新下载外，我还发现SIMD的宏默认是未启用的。
另外我发现把用了OpenMP的软渲染器改CMake工程后帧率直接翻了3倍，暂时不用改数学部分了。
日后有问题再来请教u神_(:з)∠)_

**Comment by Ubpa** [comment]
不是直接include，而是用 cmake 的 target_add_library(xxx Ubpa::UGM_core)（期间会添加库搜索路径，宏定义，编译选项），你看安装使用说明里边的使用示例

**Comment by Ubpa** [comment]
既然改成 CMake 工程了，那么就可以很简单引入库了
